name: Ubuntu SSH Direct

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl socat

          # إعداد باسورد لليوزر الافتراضي
          echo "runner:123456" | sudo chpasswd

          # تشغيل SSH
          sudo service ssh start

      - name: Expose SSH port locally
        run: |
          # فتح بورت SSH على 2222 (محليًا)
          nohup socat TCP-LISTEN:2222,fork TCP:localhost:22 > socat.log 2>&1 &
          sleep 5
          
          echo "====================================="
          echo "SSH direct command:"
          echo "ssh runner@<RUNNER_PUBLIC_IP> -p 2222"
          echo "Username: runner"
          echo "Password: 123456"
          echo "====================================="

      - name: Show Public IP
        run: |
          echo "Public IP:"
          curl -s ifconfig.me
          echo

      - name: Keep workflow alive
        run: sleep infinity
