name: Ubuntu SSH via Cloudflare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl

          # إعداد باسورد لليوزر الافتراضي
          echo "runner:123456" | sudo chpasswd

          # تشغيل SSH
          sudo service ssh start

          # تنزيل cloudflared
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared

      - name: Start Cloudflared Tunnel
        run: |
          # تشغيل النفق على بورت SSH (22)
          nohup ./cloudflared tunnel --url tcp://localhost:22 --no-autoupdate > cf.log 2>&1 &
          sleep 10
          
          # جلب رابط الاتصال الصحيح
          HOST=$(grep -oE 'https://[a-zA-Z0-9.-]+\.trycloudflare\.com' cf.log | head -n 1 | sed 's#https://##')
          
          echo "SSH command:"
          echo "ssh -o ProxyCommand=\"cloudflared access tcp --hostname $HOST\" runner@localhost"
          
          echo "====================================="
          echo "Password: 123456"
          echo "Username: runner"
          echo "====================================="

      - name: Show Public IP
        run: |
          echo "====================================="
          echo "Public IP:"
          curl -s ifconfig.me
          echo
          echo "====================================="

      - name: Keep workflow alive
        run: sleep infinity
