name: SSH via Cloudflare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH and Cloudflared
        run: |
          # تحديث النظام وتثبيت SSH و curl
          sudo apt update && sudo apt install -y openssh-server curl
          
          # تشغيل خدمة SSH
          sudo service ssh start
          
          # إعداد كلمة مرور لليوزر runner
          echo "runner:123456" | sudo chpasswd
          
          # تنزيل cloudflared
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          
          # تشغيل Cloudflared لنفق SSH وإعادة توجيه المخرجات
          nohup ./cloudflared tunnel --url tcp://localhost:22 --no-autoupdate > cloudflared.log 2>&1 &
          sleep 5
          
          # استخراج رابط الاتصال من اللوج
          SSH_URL=$(grep -oP 'https://.*trycloudflare.com' cloudflared.log | head -1)
          echo "رابط SSH مباشر:"
          echo "$SSH_URL"
          
          # إبقاء الجوب شغال
          sleep infinity
